import sys
import os

from PyQt6.QtWidgets import (
    QApplication,
    QMainWindow,
    QListWidget,
    QPushButton,
    QLabel,
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QSlider,
    QLineEdit,
    QStackedWidget,
    QFrame
)
from PyQt6.QtCore import Qt, QUrl
from PyQt6.QtGui import QPixmap, QPainter, QColor, QLinearGradient, QFont, QPen, QPainterPath, QCursor, QIcon
from PyQt6.QtMultimedia import (
    QMediaPlayer,
    QAudioOutput
)

# Mengunci path dasar ke folder tempat skrip main.py berada
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Fungsi helper untuk mengubah milidetik menjadi format waktu MM:SS
def format_time(ms):
    seconds = int((ms / 1000) % 60)
    minutes = int((ms / (1000 * 60)) % 60)
    return f"{minutes:02d}:{seconds:02d}"

# =====================================================================
# CLASS UNTUK MENGGAMBAR LOGO VECTOR OTOMATIS (HALAMAN LOGIN)
# =====================================================================
class AutoGeneratedLogo(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedSize(340, 160)

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)

        gradient = QLinearGradient(120, 20, 220, 80)
        gradient.setColorAt(0.0, QColor("#10a0e0"))
        gradient.setColorAt(0.5, QColor("#12c2e9"))
        gradient.setColorAt(1.0, QColor("#1DB954"))

        painter.setPen(QPen(gradient, 4, Qt.PenStyle.SolidLine, Qt.PenCapStyle.RoundCap))
        painter.drawLine(115, 45, 115, 65)
        painter.drawLine(123, 35, 123, 75)
        painter.drawLine(131, 25, 131, 85)
        painter.drawLine(209, 25, 209, 85)
        painter.drawLine(217, 35, 217, 75)
        painter.drawLine(225, 45, 225, 65)

        pen_u = QPen(gradient, 10, Qt.PenStyle.SolidLine, Qt.PenCapStyle.RoundCap, Qt.PenJoinStyle.RoundJoin)
        painter.setPen(pen_u)
        painter.setBrush(Qt.BrushStyle.NoBrush)
        path_u = QPainterPath()
        path_u.moveTo(148, 25)
        path_u.lineTo(148, 60)
        path_u.arcTo(148, 40, 44, 44, 180, 180)
        path_u.lineTo(192, 25)
        painter.drawPath(path_u)

        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(gradient)
        from PyQt6.QtGui import QPolygonF
        from PyQt6.QtCore import QPointF
        play_points = QPolygonF([QPointF(166, 42), QPointF(166, 62), QPointF(182, 52)])
        painter.drawPolygon(play_points)

        painter.setPen(QColor("#FFFFFF"))
        font_title = QFont("'Segoe UI', Helvetica, Arial", 25, QFont.Weight.Bold)
        font_title.setLetterSpacing(QFont.SpacingType.AbsoluteSpacing, 3)
        painter.setFont(font_title)
        painter.drawText(0, 125, 340, 40, Qt.AlignmentFlag.AlignCenter, "URRADIFY")


# =====================================================================
# 1. CLASS HALAMAN LOGIN (EFEK HOVER & FOCUS)
# =====================================================================
class LoginPage(QWidget):
    def __init__(self, controller):
        super().__init__()
        self.controller = controller
        
        main_layout = QVBoxLayout()
        main_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setLayout(main_layout)
        
        form_container = QFrame()
        form_container.setFixedWidth(400)
        form_container.setStyleSheet("""
            QFrame {
                background-color: #0e171e;
                border: 2px solid #202b36;
                border-radius: 16px;
                padding: 20px;
            }
            QLabel, QLineEdit, QPushButton { border: none; }
        """)
        
        form_layout = QVBoxLayout(form_container)
        form_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        
        self.logo_widget = AutoGeneratedLogo()
        form_layout.addWidget(self.logo_widget)

        self.subtitle = QLabel("Log In to Urradify\nBY UBE RAFI RIDO DIMAS\nALUNAN MUSIK TANPA BATAS")
        self.subtitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.subtitle.setStyleSheet("color: #a0a0a0; font-size: 11px; font-weight: bold; margin-top: 5px; margin-bottom: 20px; line-height: 16px; background: transparent;")
        form_layout.addWidget(self.subtitle)

        self.username_input = QLineEdit()
        self.username_input.setPlaceholderText("Username or Email")
        self.username_input.setFixedSize(320, 42)
        self.username_input.setStyleSheet("""
            QLineEdit {
                background-color: #17222b; color: white; border: 1px solid #202b36; border-radius: 8px; padding-left: 12px; font-size: 13px; font-weight: bold; margin-bottom: 10px;
            }
            QLineEdit:hover, QLineEdit:focus {
                border: 1px solid #1DB954;
                background-color: #1c2a35;
            }
        """)
        form_layout.addWidget(self.username_input)
        self.username_input.setText("")

        self.password_input = QLineEdit()
        self.password_input.setPlaceholderText("Password")
        self.password_input.setEchoMode(QLineEdit.EchoMode.Password)
        self.password_input.setFixedSize(320, 42)
        self.password_input.setStyleSheet("""
            QLineEdit {
                background-color: #17222b; color: white; border: 1px solid #202b36; border-radius: 8px; padding-left: 12px; font-size: 13px; font-weight: bold; margin-bottom: 10px;
            }
            QLineEdit:hover, QLineEdit:focus {
                border: 1px solid #1DB954;
                background-color: #1c2a35;
            }
        """)
        form_layout.addWidget(self.password_input)

        self.error_label = QLabel("")
        self.error_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.error_label.setStyleSheet("color: #ff3333; font-size: 12px; margin-top: 3px; margin-bottom: 3px; background: transparent;")
        form_layout.addWidget(self.error_label)

        self.login_btn = QPushButton("LOG IN ➔")
        self.login_btn.setFixedSize(320, 45)
        self.login_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.login_btn.setStyleSheet("""
            QPushButton {
                background-color: #1DB954; color: white; border-radius: 8px; font-size: 14px; font-weight: bold;
            }
            QPushButton:hover {
                background-color: #1ed760;
                font-size: 14.5px;
            }
        """)
        self.login_btn.clicked.connect(self.handle_login)
        form_layout.addWidget(self.login_btn)
        
        main_layout.addWidget(form_container)

    def handle_login(self):
        username = self.username_input.text()
        password = self.password_input.text()
        
        if username == "URRADIFY" and password == "123":
            self.error_label.setText("")
            self.controller.go_to_dashboard()
        else:
            self.error_label.setText("Username atau Password salah!")


# =====================================================================
# 2. CLASS HALAMAN DASHBOARD (MASTER PREMIUM VIEW)
# =====================================================================
class DashboardPage(QWidget):
    def __init__(self, controller):
        super().__init__()
        self.controller = controller

        self.audio_output = QAudioOutput()
        self.player = QMediaPlayer()
        self.player.setAudioOutput(self.audio_output)
        
        self.current_song = None
        self.is_paused = False  
        self.all_mp3_files = [] 

        main_layout = QHBoxLayout()
        main_layout.setContentsMargins(25, 25, 25, 25)
        main_layout.setSpacing(20)
        self.setLayout(main_layout)

        # -----------------------------------------------------------------
        # TAMPILAN SISI KIRI: MAIN PLAYER CONTROLS
        # -----------------------------------------------------------------
        left_container = QFrame()
        left_container.setStyleSheet("background-color: #0e171e; border: 1px solid #202b36; border-radius: 16px; padding: 15px;")
        left_layout = QVBoxLayout(left_container)
        left_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.title = QLabel("🎵 URRADIFY PREMIUM")
        self.title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title.setStyleSheet("font-size: 16px; letter-spacing: 2px; color: white; font-weight: bold; background: transparent;")
        left_layout.addWidget(self.title)

        # Cover Album Frame
        self.cover_label = QLabel()
        self.cover_label.setFixedSize(260, 260)
        self.cover_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cover_label.setStyleSheet("border: 2px solid #1DB954; border-radius: 12px; background-color: #070b0e; margin-top: 10px; margin-bottom: 10px;")
        left_layout.addWidget(self.cover_label, alignment=Qt.AlignmentFlag.AlignCenter)

        self.now_playing = QLabel("Now Playing : Select a Song")
        self.now_playing.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.now_playing.setStyleSheet("color: #1DB954; font-size: 13px; font-weight: bold; background: transparent; margin-bottom: 5px;")
        left_layout.addWidget(self.now_playing)

        # Timeline Slider Progres Durasi Lagu
        progress_container = QFrame()
        progress_container.setStyleSheet("background: transparent; border: none; padding: 0px;")
        progress_layout = QVBoxLayout(progress_container)
        progress_layout.setSpacing(2)

        self.progress_slider = QSlider(Qt.Orientation.Horizontal)
        self.progress_slider.setRange(0, 100)
        self.progress_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.progress_slider.setStyleSheet("""
            QSlider::groove:horizontal { height: 4px; background: #202b36; border-radius: 2px; }
            QSlider::handle:horizontal { background: #1DB954; width: 10px; margin-top: -3px; margin-bottom: -3px; border-radius: 5px; }
            QSlider::handle:horizontal:hover { background: #1ed760; width: 12px; }
            QSlider::sub-page:horizontal { background: #1DB954; border-radius: 2px; }
        """)
        
        self.time_label = QLabel("00:00 / 00:00")
        self.time_label.setAlignment(Qt.AlignmentFlag.AlignRight)
        self.time_label.setStyleSheet("color: #a0a0a0; font-size: 11px; font-family: monospace; background: transparent;")
        
        progress_layout.addWidget(self.progress_slider)
        progress_layout.addWidget(self.time_label)
        left_layout.addWidget(progress_container)

        # Layout Baris Tombol Kontrol (Prev, Play, Pause, Stop, Next)
        button_layout = QHBoxLayout()
        button_layout.setSpacing(6)
        button_layout.setContentsMargins(5, 5, 5, 5)
        
        self.prev_btn = QPushButton("⏮")
        self.prev_btn.setFixedSize(45, 38)
        self.prev_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.prev_btn.setStyleSheet("""
            QPushButton { background-color: #17222b; color: white; font-size: 14px; font-weight: bold; border-radius: 6px; border: 1px solid #202b36; }
            QPushButton:hover { background-color: #233342; border: 1px solid #1DB954; }
        """)
        
        self.play_btn = QPushButton("▶ PLAY")
        self.play_btn.setFixedSize(75, 38)
        self.play_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.play_btn.setStyleSheet("""
            QPushButton { background-color: #1DB954; color: white; font-size: 11px; font-weight: bold; border-radius: 6px; padding: 0px; }
            QPushButton:hover { background-color: #1ed760; font-size: 11.5px; }
        """)
        
        self.pause_btn = QPushButton("⏸ JEDA")
        self.pause_btn.setFixedSize(75, 38)
        self.pause_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.pause_btn.setStyleSheet("""
            QPushButton { background-color: #f39c12; color: white; font-size: 11px; font-weight: bold; border-radius: 6px; padding: 0px; }
            QPushButton:hover { background-color: #f1c40f; font-size: 11.5px; }
        """)
        
        self.stop_btn = QPushButton("⏹ STOP")
        self.stop_btn.setFixedSize(75, 38)
        self.stop_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.stop_btn.setStyleSheet("""
            QPushButton { background-color: #e74c3c; color: white; font-size: 11px; font-weight: bold; border-radius: 6px; padding: 0px; }
            QPushButton:hover { background-color: #c0392b; font-size: 11.5px; }
        """)

        self.next_btn = QPushButton("⏭")
        self.next_btn.setFixedSize(45, 38)
        self.next_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.next_btn.setStyleSheet("""
            QPushButton { background-color: #17222b; color: white; font-size: 14px; font-weight: bold; border-radius: 6px; border: 1px solid #202b36; }
            QPushButton:hover { background-color: #233342; border: 1px solid #1DB954; }
        """)

        button_layout.addWidget(self.prev_btn)
        button_layout.addWidget(self.play_btn)
        button_layout.addWidget(self.pause_btn)
        button_layout.addWidget(self.stop_btn)
        button_layout.addWidget(self.next_btn)
        left_layout.addLayout(button_layout)

        # Kontrol Volume
        volume_container = QFrame()
        volume_container.setStyleSheet("background: transparent; border: none; padding: 0px;")
        volume_layout = QHBoxLayout(volume_container)
        volume_layout.setContentsMargins(10, 5, 10, 5)
        
        self.volume_label = QLabel("🔊")
        self.volume_label.setStyleSheet("color: white; font-size: 13px; background: transparent; border: none;")
        
        self.volume_slider = QSlider(Qt.Orientation.Horizontal)
        self.volume_slider.setRange(0, 100)
        self.volume_slider.setValue(60)
        self.volume_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.audio_output.setVolume(0.6)  
        
        volume_layout.addWidget(self.volume_label)
        volume_layout.addWidget(self.volume_slider)
        left_layout.addWidget(volume_container)

        self.logout_btn = QPushButton("🚪 Log Out")
        self.logout_btn.setFixedWidth(260)
        self.logout_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.logout_btn.setStyleSheet("""
            QPushButton { background-color: #2c3e50; color: white; margin-top: 10px; padding: 8px; border-radius: 6px; font-weight: bold; border: none; }
            QPushButton:hover { background-color: #34495e; color: #ff3333; }
        """)
        self.logout_btn.clicked.connect(self.handle_logout)
        left_layout.addWidget(self.logout_btn, alignment=Qt.AlignmentFlag.AlignCenter)

        # -----------------------------------------------------------------
        # TAMPILAN SISI KANAN: LIVE SEARCH & PLAYLIST TRACKS
        # -----------------------------------------------------------------
        right_container = QFrame()
        right_container.setStyleSheet("background-color: #0e171e; border: 1px solid #202b36; border-radius: 16px; padding: 15px;")
        right_layout = QVBoxLayout(right_container)

        playlist_title = QLabel("🎶 MY TRACKS PLAYLIST")
        playlist_title.setStyleSheet("font-size: 13px; color: #a0a0a0; font-weight: bold; letter-spacing: 1px; background: transparent; border: none;")
        right_layout.addWidget(playlist_title)

        # Live Search Bar Box
        self.search_bar = QLineEdit()
        self.search_bar.setPlaceholderText("🔍 Cari judul lagu di sini...")
        self.search_bar.setStyleSheet("""
            QLineEdit {
                background-color: #070b0e; color: white; border: 1px solid #202b36; border-radius: 6px; padding-left: 10px; font-size: 12px; height: 32px; margin-bottom: 5px;
            }
            QLineEdit:hover, QLineEdit:focus {
                border: 1px solid #1DB954;
                background-color: #0d151b;
            }
        """)
        self.search_bar.textChanged.connect(self.filter_playlist)
        right_layout.addWidget(self.search_bar)

        self.songs = QListWidget()
        self.songs.setWordWrap(True) 
        self.songs.setStyleSheet("""
            QListWidget {
                background-color: #070b0e;
                color: white;
                border: 1px solid #202b36;
                border-radius: 10px;
                padding: 5px;
                font-size: 13px;
            }
            QListWidget::item {
                padding: 10px;
                border-bottom: 1px solid #141f29;
                color: #e0e0e0;
            }
            /* Efek Hover Nyala Hijau Premium saat kursor mengarah ke teks lagu */
            QListWidget::item:hover {
                background-color: #121f2b;
                color: #1DB954;
                font-weight: bold;
            }
            QListWidget::item:selected {
                background-color: #1DB954;
                color: white;
                font-weight: bold;
                border-radius: 6px;
            }
        """)
        self.load_songs_from_folder()
        right_layout.addWidget(self.songs)

        main_layout.addWidget(left_container, stretch=4)
        main_layout.addWidget(right_container, stretch=5)

        # Hubungan Event Trigger Multimedia
        self.songs.itemClicked.connect(self.song_selected)
        self.play_btn.clicked.connect(self.play_music)
        self.pause_btn.clicked.connect(self.pause_music)
        self.stop_btn.clicked.connect(self.stop_music)
        self.prev_btn.clicked.connect(self.play_prev_song)
        self.next_btn.clicked.connect(self.play_next_song)
        self.volume_slider.valueChanged.connect(self.change_volume)
        
        self.player.positionChanged.connect(self.update_position)
        self.player.durationChanged.connect(self.update_duration)
        self.progress_slider.sliderMoved.connect(self.set_music_position)
        
        self.player.mediaStatusChanged.connect(self.handle_media_status)
        self.player.errorOccurred.connect(self.media_error)

    def load_songs_from_folder(self):
        self.songs.clear()
        self.all_mp3_files = []
        music_folder = os.path.join(BASE_DIR, "music")
        if os.path.exists(music_folder):
            for file in os.listdir(music_folder):
                if file.lower().endswith(".mp3"):
                    self.all_mp3_files.append(file)
                    self.songs.addItem(file)

    def filter_playlist(self, text):
        self.songs.clear()
        for file in self.all_mp3_files:
            if text.lower() in file.lower():
                self.songs.addItem(file)

    def song_selected(self, item):
        self.current_song = os.path.join(BASE_DIR, "music", item.text())
        self.now_playing.setText(f"🎵 Playing: {item.text()}")
        
        self.is_paused = False  
        path = os.path.abspath(self.current_song)
        self.player.setSource(QUrl.fromLocalFile(path))
        self.player.play()

        song_base_name = os.path.splitext(item.text())[0]
        cover_png = os.path.join(BASE_DIR, "assets", song_base_name + ".png")
        cover_jpg = os.path.join(BASE_DIR, "assets", song_base_name + ".jpg")

        if os.path.exists(cover_png):
            self.cover_label.setPixmap(QPixmap(cover_png).scaled(260, 260, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation))
        elif os.path.exists(cover_jpg):
            self.cover_label.setPixmap(QPixmap(cover_jpg).scaled(260, 260, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation))
        else:
            self.cover_label.clear()
            self.cover_label.setText("No Album Cover")

    def play_music(self):
        if self.current_song:
            self.player.play()
            self.is_paused = False
        elif self.songs.count() > 0:
            self.songs.setCurrentRow(0)
            self.song_selected(self.songs.currentItem())

    def pause_music(self):
        if self.player.playbackState() == QMediaPlayer.PlaybackState.PlayingState:
            self.player.pause()
            self.is_paused = True

    def stop_music(self):
        self.player.stop()
        self.is_paused = False
        self.progress_slider.setValue(0)

    def play_next_song(self):
        current_row = self.songs.currentRow()
        next_row = current_row + 1
        if next_row < self.songs.count():
            self.songs.setCurrentRow(next_row)
            self.song_selected(self.songs.currentItem())
        else:
            if self.songs.count() > 0:
                self.songs.setCurrentRow(0)
                self.song_selected(self.songs.currentItem())

    def play_prev_song(self):
        current_row = self.songs.currentRow()
        prev_row = current_row - 1
        if prev_row >= 0:
            self.songs.setCurrentRow(prev_row)
            self.song_selected(self.songs.currentItem())

    def handle_media_status(self, status):
        if status == QMediaPlayer.MediaStatus.EndOfMedia:
            self.play_next_song()

    def update_position(self, position):
        if not self.progress_slider.isSliderDown():
            self.progress_slider.setValue(position)
        self.update_time_label(position, self.player.duration())

    def update_duration(self, duration):
        self.progress_slider.setRange(0, duration)
        self.update_time_label(self.player.position(), duration)

    def set_music_position(self, position):
        self.player.setPosition(position)

    def update_time_label(self, position, duration):
        self.time_label.setText(f"{format_time(position)} / {format_time(duration)}")

    def change_volume(self, value):
        self.audio_output.setVolume(value / 100)

    def media_error(self, error, message):
        print("Multimedia Player Error:", message)

    def handle_logout(self):
        self.stop_music()
        self.controller.go_to_login()


# =====================================================================
# 3. CLASS UTAMA APPLICATION CONTROLLER (SET WINDOW ICON)
# =====================================================================
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Urradify Music Player - Ultimate Master Edition")
        self.resize(1050, 680)

        # Mengganti ikon bawaan jendela aplikasi dengan file logo resmi Tuan Ube
        icon_path = os.path.join(BASE_DIR, "logo.jpg")
        if os.path.exists(icon_path):
            self.setWindowIcon(QIcon(icon_path))

        self.setStyleSheet("""
            QMainWindow, QWidget { background-color: #0b1116; }
            QSlider::groove:horizontal { height: 6px; background: #202b36; border-radius: 3px; border: none; }
            QSlider::handle:horizontal { background: #1DB954; width: 14px; margin-top: -4px; margin-bottom: -4px; border-radius: 7px; }
        """)

        self.stacked_widget = QStackedWidget()
        self.setCentralWidget(self.stacked_widget)

        self.login_page = LoginPage(self)
        self.dashboard_page = DashboardPage(self)

        self.stacked_widget.addWidget(self.login_page)
        self.stacked_widget.addWidget(self.dashboard_page)

        self.go_to_login()

    def go_to_dashboard(self):
        self.dashboard_page.load_songs_from_folder()
        self.stacked_widget.setCurrentWidget(self.dashboard_page)

    def go_to_login(self):
        self.stacked_widget.setCurrentWidget(self.login_page)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())